In [1]:
import pandas as pd
import matplotlib.pyplot as mp

In [2]:
df = pd.read_csv("C:\\Users\\migro\\Desktop\\Programming\\interactive_dash\\Video_Games.csv")
df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
genre_platform = pd.crosstab(df["Genre"], df["Platform"]).T
genre_platform

Genre,Action,Adventure,Fighting,Misc,Platform,Puzzle,Racing,Role-Playing,Shooter,Simulation,Sports,Strategy
Platform,,,,,,,,,,,,
2600,61,2,2,5,9,11,6,0,24,1,12,0
3DO,0,1,0,0,0,1,0,0,0,1,0,0
3DS,188,38,14,54,28,20,11,88,7,31,26,15
DC,3,11,12,0,2,0,6,4,3,1,10,0
DS,340,238,36,391,91,236,67,200,42,284,148,79
GB,6,5,0,8,19,15,2,21,1,5,9,7
GBA,167,38,23,110,142,41,64,73,40,18,88,18
GC,101,20,42,36,73,13,63,27,48,12,110,11
GEN,3,2,5,1,7,0,1,3,1,0,3,1
GG,0,0,0,0,1,0,0,0,0,0,0,0
N64,38,4,29,18,30,12,57,8,24,10,80,9
NES,13,1,4,2,28,14,4,11,7,0,14,0
NG,0,0,11,0,0,0,0,0,0,0,1,0
PC,170,65,6,24,11,25,61,104,150,120,50,188
PCFX,0,0,0,0,0,0,0,1,0,0,0,0
PS,157,69,108,76,64,32,145,97,96,60,222,71
PS2,348,196,150,222,103,18,216,187,160,90,400,71
PS3,380,74,76,125,37,3,92,119,156,31,214,24
PS4,144,28,18,20,12,1,19,52,41,6,46,6
PSP,222,213,74,106,36,44,63,192,37,28,134,60
PSV,150,93,16,24,9,3,11,87,5,4,23,7
SAT,3,26,31,15,5,5,8,17,22,7,16,18
SCD,0,0,0,2,1,0,1,1,0,0,0,1
SNES,12,4,25,17,26,13,9,50,10,9,49,15
TG16,0,1,0,0,0,0,0,0,1,0,0,0
WS,0,0,0,0,0,0,0,4,0,0,0,2
Wii,237,83,42,280,58,55,93,35,65,87,260,25
WiiU,64,3,5,22,17,4,3,7,10,1,8,3
X360,323,48,65,127,25,7,104,75,203,40,217,28
XB,155,26,48,46,49,7,123,23,132,24,170,21
XOne,85,14,7,19,5,0,20,14,38,4,38,3

In [47]:
genre_plat = pd.DataFrame(genre_platform.sum(axis=0))
genre_plat["Total"] = genre_plat.values
genre_plat

                 0  Total
Genre
Action        3370   3370
Adventure     1303   1303
Fighting       849    849
Misc          1750   1750
Platform       888    888
Puzzle         580    580
Racing        1249   1249
Role-Playing  1500   1500
Shooter       1323   1323
Simulation     874    874
Sports        2348   2348
Strategy       683    683

In [48]:
genre_plat["Total"].sum()

16717